### ISSUE TITLE
__metaclass__ declaration

### ISSUE THREAD

**Issue by dabada83** [fulfilio/nereid-catalog#12]
In order to this module will be compatible with Trytond 4.0, 
I think also would be compatible with Python 3.

See this link with the process to migrate one module:
https://groups.google.com/forum/#!msg/tryton-dev/3Xfox51KXaU/YS-ZiZF5AwAJ;context-place=forum/tryton-dev

The patch inside forum thread, could be used.
https://bugs.tryton.org/file2329/patch

Pull request created #13

**Comment by prakashpp** [comment]
Fixed. Thanks for pull request.
